//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Timers;
using Alchemy;
using Alchemy.Classes;

namespace PongServer
{
	public class GameRoom
	{
		UserContext firstPlayer;
		UserContext secondPlayer;

		private Timer tickTimer;
		private int ID
		{ get { return ID; } }
		
		private Game myGame;
	
		//Create a room, one player is already connected to the server
		public GameRoom(UserContext socket)
		{
			firstPlayer = socket;
			firstPlayer.Send("wait");
			Console.WriteLine("Created new room.");
		}
		
		//Let a second player join
		public void AddSecondPlayer(UserContext socket)
		{
			if(!isFull())
			{
				secondPlayer = socket;
				Console.WriteLine("A room was filled.");
				StartNewGame();
			}
			else
			{
				throw new InvalidOperationException("A third player tried to join the game!");
			}
		}

		public void RemovePlayerFromRoom(UserContext removePlayer)
		{
			if(removePlayer.Equals(firstPlayer))
			{
				firstPlayer = secondPlayer;
				secondPlayer = null;
			}
			else
			{
				secondPlayer = null;
			}

			tickTimer.Enabled = false;
			firstPlayer.Send("wait");
			Console.WriteLine("Removed player from a room.");
		}

		public List<UserContext> GetPlayers()
		{
			var playerList = new List<UserContext>();
			playerList.Add(firstPlayer);
			playerList.Add(secondPlayer);
			return playerList;
		}

		public void SetCursorPosition(UserContext sourceUser, int position)
		{
			if(!isFull())
				return;

			//If we got this position from the first player, send the position to the second player
			if(sourceUser == firstPlayer)
			{
				secondPlayer.Send("pos" + position);
				myGame.leftVerticalPos = position;
			}
			else
			{
				firstPlayer.Send("pos" + position);
				myGame.rightVerticalPos = position;
			}
		}
		
		//Let's a go
		private void StartNewGame()
		{
			SendToBoth("new");
			myGame = new Game();

			tickTimer = new Timer(26);
			tickTimer.Elapsed += Update;
			tickTimer.Enabled = true;
		}

		private void Update(object sender, ElapsedEventArgs e)
		{
			myGame.Update();
			string leftBallString = "ball" + myGame.GetBallPosition(false).ToString() + "|" + myGame.GetBallSpeed(false).x;
			string rightBallString = "ball" + myGame.GetBallPosition(true).ToString() + "|" + myGame.GetBallSpeed(true).x;
			SendToBoth(leftBallString, rightBallString);
		}
		
		private void SendToBoth(string message)
		{
			firstPlayer.Send(message);
			secondPlayer.Send(message);
		}

		private void SendToBoth(string left, string right)
		{
			firstPlayer.Send(left);
			secondPlayer.Send(right);
		}
		
		public bool isFull()
		{
			return secondPlayer != null;
		}
	}
}